sudo: required

language: python
python:
  - "3.6.4"
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo pip install docker-compose
  - pip install -r requirements.txt
before_script:
  - sudo docker-compose -f docker-compose.yml up --d


script:
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
  - coverage run -m django test --settings=tests.settings
  - docker-compose down

after_success:
  - coveralls
